# Cloud Build configuration to build and deploy the FastAPI service to Cloud Run
# Usage:
#   gcloud builds submit \
#     --config cloudbuild.yaml \
#     --substitutions=_REGION=us-central1,_SERVICE=facial-recognition-api \
#     .

substitutions:
  # Default values (can be overridden on the CLI)
  _SERVICE: facial-recognition-api
  _REGION: us-central1
  _ENV_VARS: >-
    FIREBASE_SERVICE_ACCOUNT_KEY_PATH=app/api/faacil-facial-recognition-firebase-adminsdk.json,
    FIREBASE_PROJECT_ID=faacil-facial-recognition,
    CONFIDENCE_THRESHOLD=0.6

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      [
        'run','deploy','${_SERVICE}',
        '--image','gcr.io/$PROJECT_ID/${_SERVICE}',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','8080',
        '--set-env-vars','${_ENV_VARS}'
      ]

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE}'
